<?php
	$working_directory = "http://dev.gohoody.com/";
	$domain_secondary = "http://dev.gohoody.com/";
	
	$development_status = 1;
	$version_number = 108;
	
	$facebook_app_id = "192823134073322";
	$facebook_api_key = "55566c3a36d2ee2a1cfd1cce85b6fae0";
	$facebook_app_secret = "cadcff0ca1411b30f975499ba148b8d3";

	$user='hoody';
	$host='mydbinstance2.cia6qcvecvyc.us-east-1.rds.amazonaws.com';
	$password='h00dy4u';
	$database='hoodie';
?>